// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzf4g2DuB6hoeS8zMcRgMddBwFDIxnHes',
    appId: '1:41910108979:web:32062b3642db06e78e7446',
    messagingSenderId: '41910108979',
    projectId: 'tenisu-booking',
    authDomain: 'tenisu-booking.firebaseapp.com',
    databaseURL: 'https://tenisu-booking-default-rtdb.firebaseio.com',
    storageBucket: 'tenisu-booking.appspot.com',
    measurementId: 'G-ZYGBR1WJFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HRLOuC6-kNu04WzjFjxC1flaEJyhIQc',
    appId: '1:41910108979:android:31c1d5e8667f98e68e7446',
    messagingSenderId: '41910108979',
    projectId: 'tenisu-booking',
    databaseURL: 'https://tenisu-booking-default-rtdb.firebaseio.com',
    storageBucket: 'tenisu-booking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWUofxT66qJYDYNUrquGn0a78fNe2zpTU',
    appId: '1:41910108979:ios:f6699a921cdabd378e7446',
    messagingSenderId: '41910108979',
    projectId: 'tenisu-booking',
    databaseURL: 'https://tenisu-booking-default-rtdb.firebaseio.com',
    storageBucket: 'tenisu-booking.appspot.com',
    iosClientId: '41910108979-grts5oijp76hr2eq9b4ecag0r23h62ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.feTennisbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWUofxT66qJYDYNUrquGn0a78fNe2zpTU',
    appId: '1:41910108979:ios:f6699a921cdabd378e7446',
    messagingSenderId: '41910108979',
    projectId: 'tenisu-booking',
    databaseURL: 'https://tenisu-booking-default-rtdb.firebaseio.com',
    storageBucket: 'tenisu-booking.appspot.com',
    iosClientId: '41910108979-grts5oijp76hr2eq9b4ecag0r23h62ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.feTennisbooking',
  );
}
